name: Pull Request - Check Protobuf - Go

on:
  pull_request:
    paths:
      - "proto/**.proto"

jobs:
  generate-protobuf-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21.3" # or latest go version
          check-latest: false
          cache: true
      - name: Install Dependencies
        run: |
          sudo apt-get install -y protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest
          go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest
      - name: Generate Go Source
        run: |
          make pipeline-build
      - name: Generate Go Gateway Source
        run: |
          make pipeline-build-gateway
