name: Push - Create & Tag Protobuf - Go

on:
  push:
    branches:
      - "master"
      - "main"

jobs:
  generate-protobuf-go:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21.3" # or latest go version
          check-latest: false
          cache: true
      - name: Install Dependencies
        run: |
          sudo apt-get install -y protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest
          go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest
      - name: Generate Go Source
        run: |
          make pipeline-build
      - name: Generate Go Gateway Source
        run: |
          make pipeline-build-gateway
      - name: Commit generated files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(protobuf-go): Auto-generated by Github Action"
          file_pattern: "protogen/*"
      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
